### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by MSutt** [Yoobic/install-mac#55]
https://github.com/Yoobic/install-mac/blob/b352c1e911e7297c671ed41a19ccb06af07312f5/install.sh#L86

This should be `gcloud` not `glcoud` right ?

**Comment by Edd-Strickland** [comment]
Edited however this could have been corrected via the branch and a commit being pushed to update this.  Thanks

Edd

**Comment by MSutt** [comment]
Yes I would have solved it after installing a machine if no one had done it.

I will certainly make changes this afternoon because the command line `curl https://sdk.cloud.google.com | bash` is already called 2 lines before.
